# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=256, verbose_name='Discipline name')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('teacher_name', models.CharField(max_length=256, verbose_name='Teacher name')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('date', models.DateField(verbose_name='Date')),
                ('exam_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.Exam', verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Name')),
                ('notes', models.TextField(blank=True, verbose_name='Additional notices')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='Date')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Journal',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Name')),
                ('last_name', models.CharField(max_length=256, verbose_name='Surname')),
                ('middle_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Second name')),
                ('birthday', models.DateField(null=True, verbose_name='Date of birthday')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('ticket', models.CharField(max_length=256, verbose_name='Ticket')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional notices')),
                ('student_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Group')),
            ],
            options={
                'ordering': ['last_name'],
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='student',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.Student', verbose_name='Student name'),
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student', verbose_name='Leader'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='Group'),
        ),
    ]
