# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170225_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Journal'},
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_1',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_10',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_11',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_12',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_13',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_14',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_15',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_16',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_17',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_18',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_19',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_2',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_20',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_21',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_22',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_23',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_24',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_25',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_26',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_27',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_28',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_29',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_3',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_30',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_4',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_5',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_6',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_7',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_8',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='present_day_9',
        ),
    ]
