# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20170326_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_level', models.CharField(max_length=20, verbose_name='Level')),
                ('date', models.DateTimeField()),
                ('error_message', models.CharField(max_length=1000, verbose_name='Message')),
            ],
        ),
    ]
