# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20170328_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='error_message',
            field=models.CharField(max_length=1000, verbose_name='Message'),
        ),
    ]
