# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20170329_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='error_message',
            field=models.CharField(max_length=1000, verbose_name='Messages'),
        ),
    ]
