# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20170329_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Surname'),
        ),
    ]
