# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-08 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0016_auto_20170607_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
