# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-15 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_student_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Photo'),
        ),
    ]
