# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-30 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Nicname'),
        ),
    ]
