# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-30 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='accountroles',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_roles', to=settings.AUTH_USER_MODEL, verbose_name='Account'),
        ),
    ]
