# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170530_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountroles',
            name='account',
        ),
        migrations.DeleteModel(
            name='AccountRoles',
        ),
    ]
