# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-08 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
