# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-16 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20171116_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.CharField(choices=[('manager', 'Manager'), ('guest', 'Guest')], default=django.utils.timezone.now, max_length=100, verbose_name='Account type'),
            preserve_default=False,
        ),
    ]
