# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-16 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='roles',
            new_name='role',
        ),
    ]
