# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-16 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20171116_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('guest', 'Guest')], default='guest', max_length=100, verbose_name='Account type'),
        ),
    ]
