# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-17 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='account',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
    ]
